name: Release CI
on:
  push:
    branches:
      - master
      - beta

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm run lint && pnpm run tsc

      - run: pnpm test
        env:
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}

      - name: release
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
